// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: lala/lalagov/v1/lalagov.proto

package lalagovv1

import (
	v1 "github.com/lala-protocol/lalachain/chain/api/lala/aiadvisor/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ParameterChange records an applied parameter mutation.
type ParameterChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parameter     string                 `protobuf:"bytes,1,opt,name=parameter,proto3" json:"parameter,omitempty"`
	Value         int64                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParameterChange) Reset() {
	*x = ParameterChange{}
	mi := &file_lala_lalagov_v1_lalagov_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParameterChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParameterChange) ProtoMessage() {}

func (x *ParameterChange) ProtoReflect() protoreflect.Message {
	mi := &file_lala_lalagov_v1_lalagov_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParameterChange.ProtoReflect.Descriptor instead.
func (*ParameterChange) Descriptor() ([]byte, []int) {
	return file_lala_lalagov_v1_lalagov_proto_rawDescGZIP(), []int{0}
}

func (x *ParameterChange) GetParameter() string {
	if x != nil {
		return x.Parameter
	}
	return ""
}

func (x *ParameterChange) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

// ResolvedProposal records the outcome of a governance vote.
type ResolvedProposal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Proposal      *v1.AIProposal         `protobuf:"bytes,1,opt,name=proposal,proto3" json:"proposal,omitempty"`
	VotesApprove  string                 `protobuf:"bytes,2,opt,name=votes_approve,json=votesApprove,proto3" json:"votes_approve,omitempty"` // decimal string
	VotesReject   string                 `protobuf:"bytes,3,opt,name=votes_reject,json=votesReject,proto3" json:"votes_reject,omitempty"`    // decimal string
	Outcome       string                 `protobuf:"bytes,4,opt,name=outcome,proto3" json:"outcome,omitempty"`                               // "passed" | "failed"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolvedProposal) Reset() {
	*x = ResolvedProposal{}
	mi := &file_lala_lalagov_v1_lalagov_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolvedProposal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolvedProposal) ProtoMessage() {}

func (x *ResolvedProposal) ProtoReflect() protoreflect.Message {
	mi := &file_lala_lalagov_v1_lalagov_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolvedProposal.ProtoReflect.Descriptor instead.
func (*ResolvedProposal) Descriptor() ([]byte, []int) {
	return file_lala_lalagov_v1_lalagov_proto_rawDescGZIP(), []int{1}
}

func (x *ResolvedProposal) GetProposal() *v1.AIProposal {
	if x != nil {
		return x.Proposal
	}
	return nil
}

func (x *ResolvedProposal) GetVotesApprove() string {
	if x != nil {
		return x.VotesApprove
	}
	return ""
}

func (x *ResolvedProposal) GetVotesReject() string {
	if x != nil {
		return x.VotesReject
	}
	return ""
}

func (x *ResolvedProposal) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

// GovConfig holds governance configuration parameters.
type GovConfig struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Quorum             string                 `protobuf:"bytes,1,opt,name=quorum,proto3" json:"quorum,omitempty"`     // decimal string
	Approval           string                 `protobuf:"bytes,2,opt,name=approval,proto3" json:"approval,omitempty"` // decimal string
	VotingPeriodEpochs int64                  `protobuf:"varint,3,opt,name=voting_period_epochs,json=votingPeriodEpochs,proto3" json:"voting_period_epochs,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GovConfig) Reset() {
	*x = GovConfig{}
	mi := &file_lala_lalagov_v1_lalagov_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GovConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GovConfig) ProtoMessage() {}

func (x *GovConfig) ProtoReflect() protoreflect.Message {
	mi := &file_lala_lalagov_v1_lalagov_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GovConfig.ProtoReflect.Descriptor instead.
func (*GovConfig) Descriptor() ([]byte, []int) {
	return file_lala_lalagov_v1_lalagov_proto_rawDescGZIP(), []int{2}
}

func (x *GovConfig) GetQuorum() string {
	if x != nil {
		return x.Quorum
	}
	return ""
}

func (x *GovConfig) GetApproval() string {
	if x != nil {
		return x.Approval
	}
	return ""
}

func (x *GovConfig) GetVotingPeriodEpochs() int64 {
	if x != nil {
		return x.VotingPeriodEpochs
	}
	return 0
}

// GenesisState defines the lalagov module's genesis state.
type GenesisState struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Config                  *GovConfig             `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	WhitelistedAdvisoryKeys []string               `protobuf:"bytes,2,rep,name=whitelisted_advisory_keys,json=whitelistedAdvisoryKeys,proto3" json:"whitelisted_advisory_keys,omitempty"`
	History                 []*ResolvedProposal    `protobuf:"bytes,3,rep,name=history,proto3" json:"history,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *GenesisState) Reset() {
	*x = GenesisState{}
	mi := &file_lala_lalagov_v1_lalagov_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenesisState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenesisState) ProtoMessage() {}

func (x *GenesisState) ProtoReflect() protoreflect.Message {
	mi := &file_lala_lalagov_v1_lalagov_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenesisState.ProtoReflect.Descriptor instead.
func (*GenesisState) Descriptor() ([]byte, []int) {
	return file_lala_lalagov_v1_lalagov_proto_rawDescGZIP(), []int{3}
}

func (x *GenesisState) GetConfig() *GovConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *GenesisState) GetWhitelistedAdvisoryKeys() []string {
	if x != nil {
		return x.WhitelistedAdvisoryKeys
	}
	return nil
}

func (x *GenesisState) GetHistory() []*ResolvedProposal {
	if x != nil {
		return x.History
	}
	return nil
}

var File_lala_lalagov_v1_lalagov_proto protoreflect.FileDescriptor

const file_lala_lalagov_v1_lalagov_proto_rawDesc = "" +
	"\n" +
	"\x1dlala/lalagov/v1/lalagov.proto\x12\x0flala.lalagov.v1\x1a!lala/aiadvisor/v1/aiadvisor.proto\"E\n" +
	"\x0fParameterChange\x12\x1c\n" +
	"\tparameter\x18\x01 \x01(\tR\tparameter\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value\"\xaf\x01\n" +
	"\x10ResolvedProposal\x129\n" +
	"\bproposal\x18\x01 \x01(\v2\x1d.lala.aiadvisor.v1.AIProposalR\bproposal\x12#\n" +
	"\rvotes_approve\x18\x02 \x01(\tR\fvotesApprove\x12!\n" +
	"\fvotes_reject\x18\x03 \x01(\tR\vvotesReject\x12\x18\n" +
	"\aoutcome\x18\x04 \x01(\tR\aoutcome\"q\n" +
	"\tGovConfig\x12\x16\n" +
	"\x06quorum\x18\x01 \x01(\tR\x06quorum\x12\x1a\n" +
	"\bapproval\x18\x02 \x01(\tR\bapproval\x120\n" +
	"\x14voting_period_epochs\x18\x03 \x01(\x03R\x12votingPeriodEpochs\"\xbb\x01\n" +
	"\fGenesisState\x122\n" +
	"\x06config\x18\x01 \x01(\v2\x1a.lala.lalagov.v1.GovConfigR\x06config\x12:\n" +
	"\x19whitelisted_advisory_keys\x18\x02 \x03(\tR\x17whitelistedAdvisoryKeys\x12;\n" +
	"\ahistory\x18\x03 \x03(\v2!.lala.lalagov.v1.ResolvedProposalR\ahistoryB\xd8\x01\n" +
	"\x13com.lala.lalagov.v1B\fLalagovProtoP\x01ZUgithub.com/lala-protocol/lalachain/chain/api/lala/lalagov/v1;lalagovv1\xa2\x02\x03LLX\xaa\x02\x0fLala.Lalagov.V1\xca\x02\x0fLala\\Lalagov\\V1\xe2\x02\x1bLala\\Lalagov\\V1\\GPBMetadata\xea\x02\x11Lala::Lalagov::V1b\x06proto3"

var (
	file_lala_lalagov_v1_lalagov_proto_rawDescOnce sync.Once
	file_lala_lalagov_v1_lalagov_proto_rawDescData []byte
)

func file_lala_lalagov_v1_lalagov_proto_rawDescGZIP() []byte {
	file_lala_lalagov_v1_lalagov_proto_rawDescOnce.Do(func() {
		file_lala_lalagov_v1_lalagov_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lala_lalagov_v1_lalagov_proto_rawDesc), len(file_lala_lalagov_v1_lalagov_proto_rawDesc)))
	})
	return file_lala_lalagov_v1_lalagov_proto_rawDescData
}

var file_lala_lalagov_v1_lalagov_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_lala_lalagov_v1_lalagov_proto_goTypes = []any{
	(*ParameterChange)(nil),  // 0: lala.lalagov.v1.ParameterChange
	(*ResolvedProposal)(nil), // 1: lala.lalagov.v1.ResolvedProposal
	(*GovConfig)(nil),        // 2: lala.lalagov.v1.GovConfig
	(*GenesisState)(nil),     // 3: lala.lalagov.v1.GenesisState
	(*v1.AIProposal)(nil),    // 4: lala.aiadvisor.v1.AIProposal
}
var file_lala_lalagov_v1_lalagov_proto_depIdxs = []int32{
	4, // 0: lala.lalagov.v1.ResolvedProposal.proposal:type_name -> lala.aiadvisor.v1.AIProposal
	2, // 1: lala.lalagov.v1.GenesisState.config:type_name -> lala.lalagov.v1.GovConfig
	1, // 2: lala.lalagov.v1.GenesisState.history:type_name -> lala.lalagov.v1.ResolvedProposal
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_lala_lalagov_v1_lalagov_proto_init() }
func file_lala_lalagov_v1_lalagov_proto_init() {
	if File_lala_lalagov_v1_lalagov_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lala_lalagov_v1_lalagov_proto_rawDesc), len(file_lala_lalagov_v1_lalagov_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_lala_lalagov_v1_lalagov_proto_goTypes,
		DependencyIndexes: file_lala_lalagov_v1_lalagov_proto_depIdxs,
		MessageInfos:      file_lala_lalagov_v1_lalagov_proto_msgTypes,
	}.Build()
	File_lala_lalagov_v1_lalagov_proto = out.File
	file_lala_lalagov_v1_lalagov_proto_goTypes = nil
	file_lala_lalagov_v1_lalagov_proto_depIdxs = nil
}
