// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: lala/lalagov/v1/query.proto

package lalagovv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryConfigRequest) Reset() {
	*x = QueryConfigRequest{}
	mi := &file_lala_lalagov_v1_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryConfigRequest) ProtoMessage() {}

func (x *QueryConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lala_lalagov_v1_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryConfigRequest.ProtoReflect.Descriptor instead.
func (*QueryConfigRequest) Descriptor() ([]byte, []int) {
	return file_lala_lalagov_v1_query_proto_rawDescGZIP(), []int{0}
}

type QueryConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *GovConfig             `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryConfigResponse) Reset() {
	*x = QueryConfigResponse{}
	mi := &file_lala_lalagov_v1_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryConfigResponse) ProtoMessage() {}

func (x *QueryConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lala_lalagov_v1_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryConfigResponse.ProtoReflect.Descriptor instead.
func (*QueryConfigResponse) Descriptor() ([]byte, []int) {
	return file_lala_lalagov_v1_query_proto_rawDescGZIP(), []int{1}
}

func (x *QueryConfigResponse) GetConfig() *GovConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type QueryHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryHistoryRequest) Reset() {
	*x = QueryHistoryRequest{}
	mi := &file_lala_lalagov_v1_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryHistoryRequest) ProtoMessage() {}

func (x *QueryHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lala_lalagov_v1_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryHistoryRequest.ProtoReflect.Descriptor instead.
func (*QueryHistoryRequest) Descriptor() ([]byte, []int) {
	return file_lala_lalagov_v1_query_proto_rawDescGZIP(), []int{2}
}

type QueryHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Proposals     []*ResolvedProposal    `protobuf:"bytes,1,rep,name=proposals,proto3" json:"proposals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryHistoryResponse) Reset() {
	*x = QueryHistoryResponse{}
	mi := &file_lala_lalagov_v1_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryHistoryResponse) ProtoMessage() {}

func (x *QueryHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lala_lalagov_v1_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryHistoryResponse.ProtoReflect.Descriptor instead.
func (*QueryHistoryResponse) Descriptor() ([]byte, []int) {
	return file_lala_lalagov_v1_query_proto_rawDescGZIP(), []int{3}
}

func (x *QueryHistoryResponse) GetProposals() []*ResolvedProposal {
	if x != nil {
		return x.Proposals
	}
	return nil
}

var File_lala_lalagov_v1_query_proto protoreflect.FileDescriptor

const file_lala_lalagov_v1_query_proto_rawDesc = "" +
	"\n" +
	"\x1blala/lalagov/v1/query.proto\x12\x0flala.lalagov.v1\x1a\x1dlala/lalagov/v1/lalagov.proto\"\x14\n" +
	"\x12QueryConfigRequest\"I\n" +
	"\x13QueryConfigResponse\x122\n" +
	"\x06config\x18\x01 \x01(\v2\x1a.lala.lalagov.v1.GovConfigR\x06config\"\x15\n" +
	"\x13QueryHistoryRequest\"W\n" +
	"\x14QueryHistoryResponse\x12?\n" +
	"\tproposals\x18\x01 \x03(\v2!.lala.lalagov.v1.ResolvedProposalR\tproposals2\xb4\x01\n" +
	"\x05Query\x12S\n" +
	"\x06Config\x12#.lala.lalagov.v1.QueryConfigRequest\x1a$.lala.lalagov.v1.QueryConfigResponse\x12V\n" +
	"\aHistory\x12$.lala.lalagov.v1.QueryHistoryRequest\x1a%.lala.lalagov.v1.QueryHistoryResponseB\xd6\x01\n" +
	"\x13com.lala.lalagov.v1B\n" +
	"QueryProtoP\x01ZUgithub.com/lala-protocol/lalachain/chain/api/lala/lalagov/v1;lalagovv1\xa2\x02\x03LLX\xaa\x02\x0fLala.Lalagov.V1\xca\x02\x0fLala\\Lalagov\\V1\xe2\x02\x1bLala\\Lalagov\\V1\\GPBMetadata\xea\x02\x11Lala::Lalagov::V1b\x06proto3"

var (
	file_lala_lalagov_v1_query_proto_rawDescOnce sync.Once
	file_lala_lalagov_v1_query_proto_rawDescData []byte
)

func file_lala_lalagov_v1_query_proto_rawDescGZIP() []byte {
	file_lala_lalagov_v1_query_proto_rawDescOnce.Do(func() {
		file_lala_lalagov_v1_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lala_lalagov_v1_query_proto_rawDesc), len(file_lala_lalagov_v1_query_proto_rawDesc)))
	})
	return file_lala_lalagov_v1_query_proto_rawDescData
}

var file_lala_lalagov_v1_query_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_lala_lalagov_v1_query_proto_goTypes = []any{
	(*QueryConfigRequest)(nil),   // 0: lala.lalagov.v1.QueryConfigRequest
	(*QueryConfigResponse)(nil),  // 1: lala.lalagov.v1.QueryConfigResponse
	(*QueryHistoryRequest)(nil),  // 2: lala.lalagov.v1.QueryHistoryRequest
	(*QueryHistoryResponse)(nil), // 3: lala.lalagov.v1.QueryHistoryResponse
	(*GovConfig)(nil),            // 4: lala.lalagov.v1.GovConfig
	(*ResolvedProposal)(nil),     // 5: lala.lalagov.v1.ResolvedProposal
}
var file_lala_lalagov_v1_query_proto_depIdxs = []int32{
	4, // 0: lala.lalagov.v1.QueryConfigResponse.config:type_name -> lala.lalagov.v1.GovConfig
	5, // 1: lala.lalagov.v1.QueryHistoryResponse.proposals:type_name -> lala.lalagov.v1.ResolvedProposal
	0, // 2: lala.lalagov.v1.Query.Config:input_type -> lala.lalagov.v1.QueryConfigRequest
	2, // 3: lala.lalagov.v1.Query.History:input_type -> lala.lalagov.v1.QueryHistoryRequest
	1, // 4: lala.lalagov.v1.Query.Config:output_type -> lala.lalagov.v1.QueryConfigResponse
	3, // 5: lala.lalagov.v1.Query.History:output_type -> lala.lalagov.v1.QueryHistoryResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_lala_lalagov_v1_query_proto_init() }
func file_lala_lalagov_v1_query_proto_init() {
	if File_lala_lalagov_v1_query_proto != nil {
		return
	}
	file_lala_lalagov_v1_lalagov_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lala_lalagov_v1_query_proto_rawDesc), len(file_lala_lalagov_v1_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lala_lalagov_v1_query_proto_goTypes,
		DependencyIndexes: file_lala_lalagov_v1_query_proto_depIdxs,
		MessageInfos:      file_lala_lalagov_v1_query_proto_msgTypes,
	}.Build()
	File_lala_lalagov_v1_query_proto = out.File
	file_lala_lalagov_v1_query_proto_goTypes = nil
	file_lala_lalagov_v1_query_proto_depIdxs = nil
}
