// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: lala/lalagov/v1/tx.proto

package lalagovv1

import (
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MsgVote allows validators to vote on an AI-originated proposal.
type MsgVote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProposalId    int64                  `protobuf:"varint,1,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	Voter         string                 `protobuf:"bytes,2,opt,name=voter,proto3" json:"voter,omitempty"`
	Approve       bool                   `protobuf:"varint,3,opt,name=approve,proto3" json:"approve,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgVote) Reset() {
	*x = MsgVote{}
	mi := &file_lala_lalagov_v1_tx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgVote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgVote) ProtoMessage() {}

func (x *MsgVote) ProtoReflect() protoreflect.Message {
	mi := &file_lala_lalagov_v1_tx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgVote.ProtoReflect.Descriptor instead.
func (*MsgVote) Descriptor() ([]byte, []int) {
	return file_lala_lalagov_v1_tx_proto_rawDescGZIP(), []int{0}
}

func (x *MsgVote) GetProposalId() int64 {
	if x != nil {
		return x.ProposalId
	}
	return 0
}

func (x *MsgVote) GetVoter() string {
	if x != nil {
		return x.Voter
	}
	return ""
}

func (x *MsgVote) GetApprove() bool {
	if x != nil {
		return x.Approve
	}
	return false
}

type MsgVoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgVoteResponse) Reset() {
	*x = MsgVoteResponse{}
	mi := &file_lala_lalagov_v1_tx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgVoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgVoteResponse) ProtoMessage() {}

func (x *MsgVoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lala_lalagov_v1_tx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgVoteResponse.ProtoReflect.Descriptor instead.
func (*MsgVoteResponse) Descriptor() ([]byte, []int) {
	return file_lala_lalagov_v1_tx_proto_rawDescGZIP(), []int{1}
}

var File_lala_lalagov_v1_tx_proto protoreflect.FileDescriptor

const file_lala_lalagov_v1_tx_proto_rawDesc = "" +
	"\n" +
	"\x18lala/lalagov/v1/tx.proto\x12\x0flala.lalagov.v1\x1a\x17cosmos/msg/v1/msg.proto\"f\n" +
	"\aMsgVote\x12\x1f\n" +
	"\vproposal_id\x18\x01 \x01(\x03R\n" +
	"proposalId\x12\x14\n" +
	"\x05voter\x18\x02 \x01(\tR\x05voter\x12\x18\n" +
	"\aapprove\x18\x03 \x01(\bR\aapprove:\n" +
	"\x82\xe7\xb0*\x05voter\"\x11\n" +
	"\x0fMsgVoteResponse2P\n" +
	"\x03Msg\x12B\n" +
	"\x04Vote\x12\x18.lala.lalagov.v1.MsgVote\x1a .lala.lalagov.v1.MsgVoteResponse\x1a\x05\x80\xe7\xb0*\x01B\xd3\x01\n" +
	"\x13com.lala.lalagov.v1B\aTxProtoP\x01ZUgithub.com/lala-protocol/lalachain/chain/api/lala/lalagov/v1;lalagovv1\xa2\x02\x03LLX\xaa\x02\x0fLala.Lalagov.V1\xca\x02\x0fLala\\Lalagov\\V1\xe2\x02\x1bLala\\Lalagov\\V1\\GPBMetadata\xea\x02\x11Lala::Lalagov::V1b\x06proto3"

var (
	file_lala_lalagov_v1_tx_proto_rawDescOnce sync.Once
	file_lala_lalagov_v1_tx_proto_rawDescData []byte
)

func file_lala_lalagov_v1_tx_proto_rawDescGZIP() []byte {
	file_lala_lalagov_v1_tx_proto_rawDescOnce.Do(func() {
		file_lala_lalagov_v1_tx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lala_lalagov_v1_tx_proto_rawDesc), len(file_lala_lalagov_v1_tx_proto_rawDesc)))
	})
	return file_lala_lalagov_v1_tx_proto_rawDescData
}

var file_lala_lalagov_v1_tx_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_lala_lalagov_v1_tx_proto_goTypes = []any{
	(*MsgVote)(nil),         // 0: lala.lalagov.v1.MsgVote
	(*MsgVoteResponse)(nil), // 1: lala.lalagov.v1.MsgVoteResponse
}
var file_lala_lalagov_v1_tx_proto_depIdxs = []int32{
	0, // 0: lala.lalagov.v1.Msg.Vote:input_type -> lala.lalagov.v1.MsgVote
	1, // 1: lala.lalagov.v1.Msg.Vote:output_type -> lala.lalagov.v1.MsgVoteResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_lala_lalagov_v1_tx_proto_init() }
func file_lala_lalagov_v1_tx_proto_init() {
	if File_lala_lalagov_v1_tx_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lala_lalagov_v1_tx_proto_rawDesc), len(file_lala_lalagov_v1_tx_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lala_lalagov_v1_tx_proto_goTypes,
		DependencyIndexes: file_lala_lalagov_v1_tx_proto_depIdxs,
		MessageInfos:      file_lala_lalagov_v1_tx_proto_msgTypes,
	}.Build()
	File_lala_lalagov_v1_tx_proto = out.File
	file_lala_lalagov_v1_tx_proto_goTypes = nil
	file_lala_lalagov_v1_tx_proto_depIdxs = nil
}
