// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: lala/telemetry/v1/query.proto

package telemetryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryKPIsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Epoch         int64                  `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryKPIsRequest) Reset() {
	*x = QueryKPIsRequest{}
	mi := &file_lala_telemetry_v1_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryKPIsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryKPIsRequest) ProtoMessage() {}

func (x *QueryKPIsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lala_telemetry_v1_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryKPIsRequest.ProtoReflect.Descriptor instead.
func (*QueryKPIsRequest) Descriptor() ([]byte, []int) {
	return file_lala_telemetry_v1_query_proto_rawDescGZIP(), []int{0}
}

func (x *QueryKPIsRequest) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

type QueryKPIsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kpis          *EpochKPIs             `protobuf:"bytes,1,opt,name=kpis,proto3" json:"kpis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryKPIsResponse) Reset() {
	*x = QueryKPIsResponse{}
	mi := &file_lala_telemetry_v1_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryKPIsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryKPIsResponse) ProtoMessage() {}

func (x *QueryKPIsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lala_telemetry_v1_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryKPIsResponse.ProtoReflect.Descriptor instead.
func (*QueryKPIsResponse) Descriptor() ([]byte, []int) {
	return file_lala_telemetry_v1_query_proto_rawDescGZIP(), []int{1}
}

func (x *QueryKPIsResponse) GetKpis() *EpochKPIs {
	if x != nil {
		return x.Kpis
	}
	return nil
}

type QueryAllKPIsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryAllKPIsRequest) Reset() {
	*x = QueryAllKPIsRequest{}
	mi := &file_lala_telemetry_v1_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryAllKPIsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryAllKPIsRequest) ProtoMessage() {}

func (x *QueryAllKPIsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lala_telemetry_v1_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryAllKPIsRequest.ProtoReflect.Descriptor instead.
func (*QueryAllKPIsRequest) Descriptor() ([]byte, []int) {
	return file_lala_telemetry_v1_query_proto_rawDescGZIP(), []int{2}
}

type QueryAllKPIsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kpis          []*EpochKPIs           `protobuf:"bytes,1,rep,name=kpis,proto3" json:"kpis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryAllKPIsResponse) Reset() {
	*x = QueryAllKPIsResponse{}
	mi := &file_lala_telemetry_v1_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryAllKPIsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryAllKPIsResponse) ProtoMessage() {}

func (x *QueryAllKPIsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lala_telemetry_v1_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryAllKPIsResponse.ProtoReflect.Descriptor instead.
func (*QueryAllKPIsResponse) Descriptor() ([]byte, []int) {
	return file_lala_telemetry_v1_query_proto_rawDescGZIP(), []int{3}
}

func (x *QueryAllKPIsResponse) GetKpis() []*EpochKPIs {
	if x != nil {
		return x.Kpis
	}
	return nil
}

var File_lala_telemetry_v1_query_proto protoreflect.FileDescriptor

const file_lala_telemetry_v1_query_proto_rawDesc = "" +
	"\n" +
	"\x1dlala/telemetry/v1/query.proto\x12\x11lala.telemetry.v1\x1a!lala/telemetry/v1/telemetry.proto\"(\n" +
	"\x10QueryKPIsRequest\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x03R\x05epoch\"E\n" +
	"\x11QueryKPIsResponse\x120\n" +
	"\x04kpis\x18\x01 \x01(\v2\x1c.lala.telemetry.v1.EpochKPIsR\x04kpis\"\x15\n" +
	"\x13QueryAllKPIsRequest\"H\n" +
	"\x14QueryAllKPIsResponse\x120\n" +
	"\x04kpis\x18\x01 \x03(\v2\x1c.lala.telemetry.v1.EpochKPIsR\x04kpis2\xb6\x01\n" +
	"\x05Query\x12Q\n" +
	"\x04KPIs\x12#.lala.telemetry.v1.QueryKPIsRequest\x1a$.lala.telemetry.v1.QueryKPIsResponse\x12Z\n" +
	"\aAllKPIs\x12&.lala.telemetry.v1.QueryAllKPIsRequest\x1a'.lala.telemetry.v1.QueryAllKPIsResponseB\xe4\x01\n" +
	"\x15com.lala.telemetry.v1B\n" +
	"QueryProtoP\x01ZYgithub.com/lala-protocol/lalachain/chain/api/lala/telemetry/v1;telemetryv1\xa2\x02\x03LTX\xaa\x02\x11Lala.Telemetry.V1\xca\x02\x11Lala\\Telemetry\\V1\xe2\x02\x1dLala\\Telemetry\\V1\\GPBMetadata\xea\x02\x13Lala::Telemetry::V1b\x06proto3"

var (
	file_lala_telemetry_v1_query_proto_rawDescOnce sync.Once
	file_lala_telemetry_v1_query_proto_rawDescData []byte
)

func file_lala_telemetry_v1_query_proto_rawDescGZIP() []byte {
	file_lala_telemetry_v1_query_proto_rawDescOnce.Do(func() {
		file_lala_telemetry_v1_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lala_telemetry_v1_query_proto_rawDesc), len(file_lala_telemetry_v1_query_proto_rawDesc)))
	})
	return file_lala_telemetry_v1_query_proto_rawDescData
}

var file_lala_telemetry_v1_query_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_lala_telemetry_v1_query_proto_goTypes = []any{
	(*QueryKPIsRequest)(nil),     // 0: lala.telemetry.v1.QueryKPIsRequest
	(*QueryKPIsResponse)(nil),    // 1: lala.telemetry.v1.QueryKPIsResponse
	(*QueryAllKPIsRequest)(nil),  // 2: lala.telemetry.v1.QueryAllKPIsRequest
	(*QueryAllKPIsResponse)(nil), // 3: lala.telemetry.v1.QueryAllKPIsResponse
	(*EpochKPIs)(nil),            // 4: lala.telemetry.v1.EpochKPIs
}
var file_lala_telemetry_v1_query_proto_depIdxs = []int32{
	4, // 0: lala.telemetry.v1.QueryKPIsResponse.kpis:type_name -> lala.telemetry.v1.EpochKPIs
	4, // 1: lala.telemetry.v1.QueryAllKPIsResponse.kpis:type_name -> lala.telemetry.v1.EpochKPIs
	0, // 2: lala.telemetry.v1.Query.KPIs:input_type -> lala.telemetry.v1.QueryKPIsRequest
	2, // 3: lala.telemetry.v1.Query.AllKPIs:input_type -> lala.telemetry.v1.QueryAllKPIsRequest
	1, // 4: lala.telemetry.v1.Query.KPIs:output_type -> lala.telemetry.v1.QueryKPIsResponse
	3, // 5: lala.telemetry.v1.Query.AllKPIs:output_type -> lala.telemetry.v1.QueryAllKPIsResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_lala_telemetry_v1_query_proto_init() }
func file_lala_telemetry_v1_query_proto_init() {
	if File_lala_telemetry_v1_query_proto != nil {
		return
	}
	file_lala_telemetry_v1_telemetry_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lala_telemetry_v1_query_proto_rawDesc), len(file_lala_telemetry_v1_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lala_telemetry_v1_query_proto_goTypes,
		DependencyIndexes: file_lala_telemetry_v1_query_proto_depIdxs,
		MessageInfos:      file_lala_telemetry_v1_query_proto_msgTypes,
	}.Build()
	File_lala_telemetry_v1_query_proto = out.File
	file_lala_telemetry_v1_query_proto_goTypes = nil
	file_lala_telemetry_v1_query_proto_depIdxs = nil
}
