// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: lala/telemetry/v1/query.proto

package telemetryv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Query_KPIs_FullMethodName    = "/lala.telemetry.v1.Query/KPIs"
	Query_AllKPIs_FullMethodName = "/lala.telemetry.v1.Query/AllKPIs"
)

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Query defines the gRPC querier service for the telemetry module.
type QueryClient interface {
	// KPIs returns the KPIs for a specific epoch.
	KPIs(ctx context.Context, in *QueryKPIsRequest, opts ...grpc.CallOption) (*QueryKPIsResponse, error)
	// AllKPIs returns the full KPI history.
	AllKPIs(ctx context.Context, in *QueryAllKPIsRequest, opts ...grpc.CallOption) (*QueryAllKPIsResponse, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) KPIs(ctx context.Context, in *QueryKPIsRequest, opts ...grpc.CallOption) (*QueryKPIsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryKPIsResponse)
	err := c.cc.Invoke(ctx, Query_KPIs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AllKPIs(ctx context.Context, in *QueryAllKPIsRequest, opts ...grpc.CallOption) (*QueryAllKPIsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryAllKPIsResponse)
	err := c.cc.Invoke(ctx, Query_AllKPIs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
// All implementations must embed UnimplementedQueryServer
// for forward compatibility.
//
// Query defines the gRPC querier service for the telemetry module.
type QueryServer interface {
	// KPIs returns the KPIs for a specific epoch.
	KPIs(context.Context, *QueryKPIsRequest) (*QueryKPIsResponse, error)
	// AllKPIs returns the full KPI history.
	AllKPIs(context.Context, *QueryAllKPIsRequest) (*QueryAllKPIsResponse, error)
	mustEmbedUnimplementedQueryServer()
}

// UnimplementedQueryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQueryServer struct{}

func (UnimplementedQueryServer) KPIs(context.Context, *QueryKPIsRequest) (*QueryKPIsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KPIs not implemented")
}
func (UnimplementedQueryServer) AllKPIs(context.Context, *QueryAllKPIsRequest) (*QueryAllKPIsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AllKPIs not implemented")
}
func (UnimplementedQueryServer) mustEmbedUnimplementedQueryServer() {}
func (UnimplementedQueryServer) testEmbeddedByValue()               {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	// If the following call panics, it indicates UnimplementedQueryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_KPIs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryKPIsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).KPIs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_KPIs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).KPIs(ctx, req.(*QueryKPIsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AllKPIs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllKPIsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AllKPIs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_AllKPIs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AllKPIs(ctx, req.(*QueryAllKPIsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lala.telemetry.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "KPIs",
			Handler:    _Query_KPIs_Handler,
		},
		{
			MethodName: "AllKPIs",
			Handler:    _Query_AllKPIs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lala/telemetry/v1/query.proto",
}
