// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: lala/telemetry/v1/telemetry.proto

package telemetryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EpochKPIs are computed once per epoch from finalized block data.
type EpochKPIs struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Epoch             int64                  `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	AvgBlockTimeMs    string                 `protobuf:"bytes,2,opt,name=avg_block_time_ms,json=avgBlockTimeMs,proto3" json:"avg_block_time_ms,omitempty"` // stored as string for decimal precision
	BlockTimeVariance string                 `protobuf:"bytes,3,opt,name=block_time_variance,json=blockTimeVariance,proto3" json:"block_time_variance,omitempty"`
	AvgUtilization    string                 `protobuf:"bytes,4,opt,name=avg_utilization,json=avgUtilization,proto3" json:"avg_utilization,omitempty"`
	AvgBaseFee        int64                  `protobuf:"varint,5,opt,name=avg_base_fee,json=avgBaseFee,proto3" json:"avg_base_fee,omitempty"`
	ValidatorCount    int32                  `protobuf:"varint,6,opt,name=validator_count,json=validatorCount,proto3" json:"validator_count,omitempty"`
	TotalStakedRatio  string                 `protobuf:"bytes,7,opt,name=total_staked_ratio,json=totalStakedRatio,proto3" json:"total_staked_ratio,omitempty"`
	MempoolSizeTrend  string                 `protobuf:"bytes,8,opt,name=mempool_size_trend,json=mempoolSizeTrend,proto3" json:"mempool_size_trend,omitempty"`
	SlashingEvents    int64                  `protobuf:"varint,9,opt,name=slashing_events,json=slashingEvents,proto3" json:"slashing_events,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EpochKPIs) Reset() {
	*x = EpochKPIs{}
	mi := &file_lala_telemetry_v1_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EpochKPIs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EpochKPIs) ProtoMessage() {}

func (x *EpochKPIs) ProtoReflect() protoreflect.Message {
	mi := &file_lala_telemetry_v1_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EpochKPIs.ProtoReflect.Descriptor instead.
func (*EpochKPIs) Descriptor() ([]byte, []int) {
	return file_lala_telemetry_v1_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *EpochKPIs) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *EpochKPIs) GetAvgBlockTimeMs() string {
	if x != nil {
		return x.AvgBlockTimeMs
	}
	return ""
}

func (x *EpochKPIs) GetBlockTimeVariance() string {
	if x != nil {
		return x.BlockTimeVariance
	}
	return ""
}

func (x *EpochKPIs) GetAvgUtilization() string {
	if x != nil {
		return x.AvgUtilization
	}
	return ""
}

func (x *EpochKPIs) GetAvgBaseFee() int64 {
	if x != nil {
		return x.AvgBaseFee
	}
	return 0
}

func (x *EpochKPIs) GetValidatorCount() int32 {
	if x != nil {
		return x.ValidatorCount
	}
	return 0
}

func (x *EpochKPIs) GetTotalStakedRatio() string {
	if x != nil {
		return x.TotalStakedRatio
	}
	return ""
}

func (x *EpochKPIs) GetMempoolSizeTrend() string {
	if x != nil {
		return x.MempoolSizeTrend
	}
	return ""
}

func (x *EpochKPIs) GetSlashingEvents() int64 {
	if x != nil {
		return x.SlashingEvents
	}
	return 0
}

// GenesisState defines the telemetry module's genesis state.
type GenesisState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KpiHistory    []*EpochKPIs           `protobuf:"bytes,1,rep,name=kpi_history,json=kpiHistory,proto3" json:"kpi_history,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenesisState) Reset() {
	*x = GenesisState{}
	mi := &file_lala_telemetry_v1_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenesisState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenesisState) ProtoMessage() {}

func (x *GenesisState) ProtoReflect() protoreflect.Message {
	mi := &file_lala_telemetry_v1_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenesisState.ProtoReflect.Descriptor instead.
func (*GenesisState) Descriptor() ([]byte, []int) {
	return file_lala_telemetry_v1_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *GenesisState) GetKpiHistory() []*EpochKPIs {
	if x != nil {
		return x.KpiHistory
	}
	return nil
}

var File_lala_telemetry_v1_telemetry_proto protoreflect.FileDescriptor

const file_lala_telemetry_v1_telemetry_proto_rawDesc = "" +
	"\n" +
	"!lala/telemetry/v1/telemetry.proto\x12\x11lala.telemetry.v1\"\xf5\x02\n" +
	"\tEpochKPIs\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x03R\x05epoch\x12)\n" +
	"\x11avg_block_time_ms\x18\x02 \x01(\tR\x0eavgBlockTimeMs\x12.\n" +
	"\x13block_time_variance\x18\x03 \x01(\tR\x11blockTimeVariance\x12'\n" +
	"\x0favg_utilization\x18\x04 \x01(\tR\x0eavgUtilization\x12 \n" +
	"\favg_base_fee\x18\x05 \x01(\x03R\n" +
	"avgBaseFee\x12'\n" +
	"\x0fvalidator_count\x18\x06 \x01(\x05R\x0evalidatorCount\x12,\n" +
	"\x12total_staked_ratio\x18\a \x01(\tR\x10totalStakedRatio\x12,\n" +
	"\x12mempool_size_trend\x18\b \x01(\tR\x10mempoolSizeTrend\x12'\n" +
	"\x0fslashing_events\x18\t \x01(\x03R\x0eslashingEvents\"M\n" +
	"\fGenesisState\x12=\n" +
	"\vkpi_history\x18\x01 \x03(\v2\x1c.lala.telemetry.v1.EpochKPIsR\n" +
	"kpiHistoryB\xe8\x01\n" +
	"\x15com.lala.telemetry.v1B\x0eTelemetryProtoP\x01ZYgithub.com/lala-protocol/lalachain/chain/api/lala/telemetry/v1;telemetryv1\xa2\x02\x03LTX\xaa\x02\x11Lala.Telemetry.V1\xca\x02\x11Lala\\Telemetry\\V1\xe2\x02\x1dLala\\Telemetry\\V1\\GPBMetadata\xea\x02\x13Lala::Telemetry::V1b\x06proto3"

var (
	file_lala_telemetry_v1_telemetry_proto_rawDescOnce sync.Once
	file_lala_telemetry_v1_telemetry_proto_rawDescData []byte
)

func file_lala_telemetry_v1_telemetry_proto_rawDescGZIP() []byte {
	file_lala_telemetry_v1_telemetry_proto_rawDescOnce.Do(func() {
		file_lala_telemetry_v1_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lala_telemetry_v1_telemetry_proto_rawDesc), len(file_lala_telemetry_v1_telemetry_proto_rawDesc)))
	})
	return file_lala_telemetry_v1_telemetry_proto_rawDescData
}

var file_lala_telemetry_v1_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_lala_telemetry_v1_telemetry_proto_goTypes = []any{
	(*EpochKPIs)(nil),    // 0: lala.telemetry.v1.EpochKPIs
	(*GenesisState)(nil), // 1: lala.telemetry.v1.GenesisState
}
var file_lala_telemetry_v1_telemetry_proto_depIdxs = []int32{
	0, // 0: lala.telemetry.v1.GenesisState.kpi_history:type_name -> lala.telemetry.v1.EpochKPIs
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_lala_telemetry_v1_telemetry_proto_init() }
func file_lala_telemetry_v1_telemetry_proto_init() {
	if File_lala_telemetry_v1_telemetry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lala_telemetry_v1_telemetry_proto_rawDesc), len(file_lala_telemetry_v1_telemetry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_lala_telemetry_v1_telemetry_proto_goTypes,
		DependencyIndexes: file_lala_telemetry_v1_telemetry_proto_depIdxs,
		MessageInfos:      file_lala_telemetry_v1_telemetry_proto_msgTypes,
	}.Build()
	File_lala_telemetry_v1_telemetry_proto = out.File
	file_lala_telemetry_v1_telemetry_proto_goTypes = nil
	file_lala_telemetry_v1_telemetry_proto_depIdxs = nil
}
