// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: lala/aiadvisor/v1/aiadvisor.proto

package aiadvisorv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AIProposal represents a parameter change proposal originated by the AI advisor.
type AIProposal struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ProposalId        int64                  `protobuf:"varint,1,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	EpochSubmitted    int64                  `protobuf:"varint,2,opt,name=epoch_submitted,json=epochSubmitted,proto3" json:"epoch_submitted,omitempty"`
	Parameter         string                 `protobuf:"bytes,3,opt,name=parameter,proto3" json:"parameter,omitempty"`
	CurrentValue      int64                  `protobuf:"varint,4,opt,name=current_value,json=currentValue,proto3" json:"current_value,omitempty"`
	ProposedValue     int64                  `protobuf:"varint,5,opt,name=proposed_value,json=proposedValue,proto3" json:"proposed_value,omitempty"`
	Rationale         string                 `protobuf:"bytes,6,opt,name=rationale,proto3" json:"rationale,omitempty"`
	ActivationEpoch   int64                  `protobuf:"varint,7,opt,name=activation_epoch,json=activationEpoch,proto3" json:"activation_epoch,omitempty"`
	AdvisoryKey       string                 `protobuf:"bytes,8,opt,name=advisory_key,json=advisoryKey,proto3" json:"advisory_key,omitempty"`
	AdvisorySignature string                 `protobuf:"bytes,9,opt,name=advisory_signature,json=advisorySignature,proto3" json:"advisory_signature,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AIProposal) Reset() {
	*x = AIProposal{}
	mi := &file_lala_aiadvisor_v1_aiadvisor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AIProposal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIProposal) ProtoMessage() {}

func (x *AIProposal) ProtoReflect() protoreflect.Message {
	mi := &file_lala_aiadvisor_v1_aiadvisor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIProposal.ProtoReflect.Descriptor instead.
func (*AIProposal) Descriptor() ([]byte, []int) {
	return file_lala_aiadvisor_v1_aiadvisor_proto_rawDescGZIP(), []int{0}
}

func (x *AIProposal) GetProposalId() int64 {
	if x != nil {
		return x.ProposalId
	}
	return 0
}

func (x *AIProposal) GetEpochSubmitted() int64 {
	if x != nil {
		return x.EpochSubmitted
	}
	return 0
}

func (x *AIProposal) GetParameter() string {
	if x != nil {
		return x.Parameter
	}
	return ""
}

func (x *AIProposal) GetCurrentValue() int64 {
	if x != nil {
		return x.CurrentValue
	}
	return 0
}

func (x *AIProposal) GetProposedValue() int64 {
	if x != nil {
		return x.ProposedValue
	}
	return 0
}

func (x *AIProposal) GetRationale() string {
	if x != nil {
		return x.Rationale
	}
	return ""
}

func (x *AIProposal) GetActivationEpoch() int64 {
	if x != nil {
		return x.ActivationEpoch
	}
	return 0
}

func (x *AIProposal) GetAdvisoryKey() string {
	if x != nil {
		return x.AdvisoryKey
	}
	return ""
}

func (x *AIProposal) GetAdvisorySignature() string {
	if x != nil {
		return x.AdvisorySignature
	}
	return ""
}

// AdvisorState captures the persisted advisor state.
type AdvisorState struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NextProposalId int64                  `protobuf:"varint,1,opt,name=next_proposal_id,json=nextProposalId,proto3" json:"next_proposal_id,omitempty"`
	LowUtilStreak  int64                  `protobuf:"varint,2,opt,name=low_util_streak,json=lowUtilStreak,proto3" json:"low_util_streak,omitempty"`
	HighUtilStreak int64                  `protobuf:"varint,3,opt,name=high_util_streak,json=highUtilStreak,proto3" json:"high_util_streak,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AdvisorState) Reset() {
	*x = AdvisorState{}
	mi := &file_lala_aiadvisor_v1_aiadvisor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdvisorState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdvisorState) ProtoMessage() {}

func (x *AdvisorState) ProtoReflect() protoreflect.Message {
	mi := &file_lala_aiadvisor_v1_aiadvisor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdvisorState.ProtoReflect.Descriptor instead.
func (*AdvisorState) Descriptor() ([]byte, []int) {
	return file_lala_aiadvisor_v1_aiadvisor_proto_rawDescGZIP(), []int{1}
}

func (x *AdvisorState) GetNextProposalId() int64 {
	if x != nil {
		return x.NextProposalId
	}
	return 0
}

func (x *AdvisorState) GetLowUtilStreak() int64 {
	if x != nil {
		return x.LowUtilStreak
	}
	return 0
}

func (x *AdvisorState) GetHighUtilStreak() int64 {
	if x != nil {
		return x.HighUtilStreak
	}
	return 0
}

// GenesisState defines the aiadvisor module's genesis state.
type GenesisState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         *AdvisorState          `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	AdvisoryKey   string                 `protobuf:"bytes,2,opt,name=advisory_key,json=advisoryKey,proto3" json:"advisory_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenesisState) Reset() {
	*x = GenesisState{}
	mi := &file_lala_aiadvisor_v1_aiadvisor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenesisState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenesisState) ProtoMessage() {}

func (x *GenesisState) ProtoReflect() protoreflect.Message {
	mi := &file_lala_aiadvisor_v1_aiadvisor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenesisState.ProtoReflect.Descriptor instead.
func (*GenesisState) Descriptor() ([]byte, []int) {
	return file_lala_aiadvisor_v1_aiadvisor_proto_rawDescGZIP(), []int{2}
}

func (x *GenesisState) GetState() *AdvisorState {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *GenesisState) GetAdvisoryKey() string {
	if x != nil {
		return x.AdvisoryKey
	}
	return ""
}

var File_lala_aiadvisor_v1_aiadvisor_proto protoreflect.FileDescriptor

const file_lala_aiadvisor_v1_aiadvisor_proto_rawDesc = "" +
	"\n" +
	"!lala/aiadvisor/v1/aiadvisor.proto\x12\x11lala.aiadvisor.v1\"\xdb\x02\n" +
	"\n" +
	"AIProposal\x12\x1f\n" +
	"\vproposal_id\x18\x01 \x01(\x03R\n" +
	"proposalId\x12'\n" +
	"\x0fepoch_submitted\x18\x02 \x01(\x03R\x0eepochSubmitted\x12\x1c\n" +
	"\tparameter\x18\x03 \x01(\tR\tparameter\x12#\n" +
	"\rcurrent_value\x18\x04 \x01(\x03R\fcurrentValue\x12%\n" +
	"\x0eproposed_value\x18\x05 \x01(\x03R\rproposedValue\x12\x1c\n" +
	"\trationale\x18\x06 \x01(\tR\trationale\x12)\n" +
	"\x10activation_epoch\x18\a \x01(\x03R\x0factivationEpoch\x12!\n" +
	"\fadvisory_key\x18\b \x01(\tR\vadvisoryKey\x12-\n" +
	"\x12advisory_signature\x18\t \x01(\tR\x11advisorySignature\"\x8a\x01\n" +
	"\fAdvisorState\x12(\n" +
	"\x10next_proposal_id\x18\x01 \x01(\x03R\x0enextProposalId\x12&\n" +
	"\x0flow_util_streak\x18\x02 \x01(\x03R\rlowUtilStreak\x12(\n" +
	"\x10high_util_streak\x18\x03 \x01(\x03R\x0ehighUtilStreak\"h\n" +
	"\fGenesisState\x125\n" +
	"\x05state\x18\x01 \x01(\v2\x1f.lala.aiadvisor.v1.AdvisorStateR\x05state\x12!\n" +
	"\fadvisory_key\x18\x02 \x01(\tR\vadvisoryKeyB\xe8\x01\n" +
	"\x15com.lala.aiadvisor.v1B\x0eAiadvisorProtoP\x01ZYgithub.com/lala-protocol/lalachain/chain/api/lala/aiadvisor/v1;aiadvisorv1\xa2\x02\x03LAX\xaa\x02\x11Lala.Aiadvisor.V1\xca\x02\x11Lala\\Aiadvisor\\V1\xe2\x02\x1dLala\\Aiadvisor\\V1\\GPBMetadata\xea\x02\x13Lala::Aiadvisor::V1b\x06proto3"

var (
	file_lala_aiadvisor_v1_aiadvisor_proto_rawDescOnce sync.Once
	file_lala_aiadvisor_v1_aiadvisor_proto_rawDescData []byte
)

func file_lala_aiadvisor_v1_aiadvisor_proto_rawDescGZIP() []byte {
	file_lala_aiadvisor_v1_aiadvisor_proto_rawDescOnce.Do(func() {
		file_lala_aiadvisor_v1_aiadvisor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lala_aiadvisor_v1_aiadvisor_proto_rawDesc), len(file_lala_aiadvisor_v1_aiadvisor_proto_rawDesc)))
	})
	return file_lala_aiadvisor_v1_aiadvisor_proto_rawDescData
}

var file_lala_aiadvisor_v1_aiadvisor_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_lala_aiadvisor_v1_aiadvisor_proto_goTypes = []any{
	(*AIProposal)(nil),   // 0: lala.aiadvisor.v1.AIProposal
	(*AdvisorState)(nil), // 1: lala.aiadvisor.v1.AdvisorState
	(*GenesisState)(nil), // 2: lala.aiadvisor.v1.GenesisState
}
var file_lala_aiadvisor_v1_aiadvisor_proto_depIdxs = []int32{
	1, // 0: lala.aiadvisor.v1.GenesisState.state:type_name -> lala.aiadvisor.v1.AdvisorState
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_lala_aiadvisor_v1_aiadvisor_proto_init() }
func file_lala_aiadvisor_v1_aiadvisor_proto_init() {
	if File_lala_aiadvisor_v1_aiadvisor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lala_aiadvisor_v1_aiadvisor_proto_rawDesc), len(file_lala_aiadvisor_v1_aiadvisor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_lala_aiadvisor_v1_aiadvisor_proto_goTypes,
		DependencyIndexes: file_lala_aiadvisor_v1_aiadvisor_proto_depIdxs,
		MessageInfos:      file_lala_aiadvisor_v1_aiadvisor_proto_msgTypes,
	}.Build()
	File_lala_aiadvisor_v1_aiadvisor_proto = out.File
	file_lala_aiadvisor_v1_aiadvisor_proto_goTypes = nil
	file_lala_aiadvisor_v1_aiadvisor_proto_depIdxs = nil
}
