// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: lala/aiadvisor/v1/query.proto

package aiadvisorv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryStateRequest) Reset() {
	*x = QueryStateRequest{}
	mi := &file_lala_aiadvisor_v1_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryStateRequest) ProtoMessage() {}

func (x *QueryStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lala_aiadvisor_v1_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryStateRequest.ProtoReflect.Descriptor instead.
func (*QueryStateRequest) Descriptor() ([]byte, []int) {
	return file_lala_aiadvisor_v1_query_proto_rawDescGZIP(), []int{0}
}

type QueryStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         *AdvisorState          `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryStateResponse) Reset() {
	*x = QueryStateResponse{}
	mi := &file_lala_aiadvisor_v1_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryStateResponse) ProtoMessage() {}

func (x *QueryStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lala_aiadvisor_v1_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryStateResponse.ProtoReflect.Descriptor instead.
func (*QueryStateResponse) Descriptor() ([]byte, []int) {
	return file_lala_aiadvisor_v1_query_proto_rawDescGZIP(), []int{1}
}

func (x *QueryStateResponse) GetState() *AdvisorState {
	if x != nil {
		return x.State
	}
	return nil
}

var File_lala_aiadvisor_v1_query_proto protoreflect.FileDescriptor

const file_lala_aiadvisor_v1_query_proto_rawDesc = "" +
	"\n" +
	"\x1dlala/aiadvisor/v1/query.proto\x12\x11lala.aiadvisor.v1\x1a!lala/aiadvisor/v1/aiadvisor.proto\"\x13\n" +
	"\x11QueryStateRequest\"K\n" +
	"\x12QueryStateResponse\x125\n" +
	"\x05state\x18\x01 \x01(\v2\x1f.lala.aiadvisor.v1.AdvisorStateR\x05state2]\n" +
	"\x05Query\x12T\n" +
	"\x05State\x12$.lala.aiadvisor.v1.QueryStateRequest\x1a%.lala.aiadvisor.v1.QueryStateResponseB\xe4\x01\n" +
	"\x15com.lala.aiadvisor.v1B\n" +
	"QueryProtoP\x01ZYgithub.com/lala-protocol/lalachain/chain/api/lala/aiadvisor/v1;aiadvisorv1\xa2\x02\x03LAX\xaa\x02\x11Lala.Aiadvisor.V1\xca\x02\x11Lala\\Aiadvisor\\V1\xe2\x02\x1dLala\\Aiadvisor\\V1\\GPBMetadata\xea\x02\x13Lala::Aiadvisor::V1b\x06proto3"

var (
	file_lala_aiadvisor_v1_query_proto_rawDescOnce sync.Once
	file_lala_aiadvisor_v1_query_proto_rawDescData []byte
)

func file_lala_aiadvisor_v1_query_proto_rawDescGZIP() []byte {
	file_lala_aiadvisor_v1_query_proto_rawDescOnce.Do(func() {
		file_lala_aiadvisor_v1_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lala_aiadvisor_v1_query_proto_rawDesc), len(file_lala_aiadvisor_v1_query_proto_rawDesc)))
	})
	return file_lala_aiadvisor_v1_query_proto_rawDescData
}

var file_lala_aiadvisor_v1_query_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_lala_aiadvisor_v1_query_proto_goTypes = []any{
	(*QueryStateRequest)(nil),  // 0: lala.aiadvisor.v1.QueryStateRequest
	(*QueryStateResponse)(nil), // 1: lala.aiadvisor.v1.QueryStateResponse
	(*AdvisorState)(nil),       // 2: lala.aiadvisor.v1.AdvisorState
}
var file_lala_aiadvisor_v1_query_proto_depIdxs = []int32{
	2, // 0: lala.aiadvisor.v1.QueryStateResponse.state:type_name -> lala.aiadvisor.v1.AdvisorState
	0, // 1: lala.aiadvisor.v1.Query.State:input_type -> lala.aiadvisor.v1.QueryStateRequest
	1, // 2: lala.aiadvisor.v1.Query.State:output_type -> lala.aiadvisor.v1.QueryStateResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_lala_aiadvisor_v1_query_proto_init() }
func file_lala_aiadvisor_v1_query_proto_init() {
	if File_lala_aiadvisor_v1_query_proto != nil {
		return
	}
	file_lala_aiadvisor_v1_aiadvisor_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lala_aiadvisor_v1_query_proto_rawDesc), len(file_lala_aiadvisor_v1_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lala_aiadvisor_v1_query_proto_goTypes,
		DependencyIndexes: file_lala_aiadvisor_v1_query_proto_depIdxs,
		MessageInfos:      file_lala_aiadvisor_v1_query_proto_msgTypes,
	}.Build()
	File_lala_aiadvisor_v1_query_proto = out.File
	file_lala_aiadvisor_v1_query_proto_goTypes = nil
	file_lala_aiadvisor_v1_query_proto_depIdxs = nil
}
