"""
Lala Protocol — Adaptation Loop Simulation
============================================
This script provides a minimal, self-contained Python simulation of the
four-component architecture described in the Lala Protocol whitepaper:

  1. Base Consensus Layer (PoS)  — mocked as a simple epoch-driven state.
  2. Network Telemetry Module    — derives KPIs from synthetic block data.
  3. AI Advisory Module          — rule-based advisor that proposes parameter
                                   changes when KPIs fall outside target ranges.
  4. Governance Layer            — stake-weighted voting by a validator set.

Usage
-----
    python simulation.py              # run 30 epochs with default settings
    python simulation.py --epochs 60  # run 60 epochs
    python simulation.py --seed 42    # reproducible run

The simulation prints a per-epoch summary and a final report showing which
parameter adjustments were ratified and how the network state evolved.
"""

from __future__ import annotations

import argparse
import random
import statistics
from dataclasses import dataclass, field
from typing import Dict, List, Optional


# ---------------------------------------------------------------------------
# Data Structures
# ---------------------------------------------------------------------------

@dataclass
class NetworkParams:
    """Protocol parameters that the AI Advisory Module may propose to change."""
    block_gas_limit: int = 15_000_000    # gas units per block
    base_fee_per_gas: int = 1_000_000_000  # wei (1 Gwei)
    target_block_time_ms: int = 6_000    # milliseconds


@dataclass
class EpochKPIs:
    """Telemetry KPIs computed at the end of each epoch."""
    epoch: int
    avg_block_time_ms: float
    block_time_variance_ms: float
    avg_utilization: float          # 0.0 – 1.0 (gas used / gas limit)
    avg_base_fee: int               # wei
    validator_count: int
    total_staked_ratio: float       # staked / total supply, 0.0 – 1.0
    mempool_size_trend: float       # positive = growing, negative = shrinking
    slashing_events: int


@dataclass
class Proposal:
    """A parameter-change proposal generated by the AI Advisory Module."""
    proposal_id: int
    epoch_submitted: int
    parameter: str
    current_value: int
    proposed_value: int
    rationale: str
    activation_epoch: int
    votes_approve: float = 0.0      # total stake that voted Approve
    votes_reject: float = 0.0       # total stake that voted Reject
    outcome: Optional[str] = None   # "passed" | "failed" | None (pending)


@dataclass
class Validator:
    """A single PoS validator."""
    address: str
    stake: float                    # normalised stake weight (0.0 – 1.0)
    conservative: bool = False      # conservative validators reject large changes


# ---------------------------------------------------------------------------
# 1. Base Consensus Layer (mocked)
# ---------------------------------------------------------------------------

class BaseConsensusLayer:
    """
    Minimal mock of the PoS consensus layer.  Each epoch it produces a list
    of synthetic blocks whose attributes are drawn from distributions that
    depend on the current network parameters.
    """

    BLOCKS_PER_EPOCH: int = 50

    def __init__(self, params: NetworkParams, rng: random.Random) -> None:
        self.params = params
        self.rng = rng

    def produce_epoch_blocks(self, demand_level: float) -> List[Dict]:
        """
        Simulate blocks for one epoch.

        demand_level : 0.0 – 1.0 representing relative transaction demand.
        """
        blocks = []
        for _ in range(self.BLOCKS_PER_EPOCH):
            # Block time jitter around the target
            jitter = self.rng.gauss(0, self.params.target_block_time_ms * 0.05)
            block_time = max(1_000, self.params.target_block_time_ms + jitter)

            # Gas utilization driven by demand; capped at 1.0
            raw_util = demand_level * self.rng.gauss(1.0, 0.15)
            utilization = min(1.0, max(0.0, raw_util))
            gas_used = int(self.params.block_gas_limit * utilization)

            # Base fee: increases when utilization > 0.5, decreases below
            fee_adjustment = (utilization - 0.5) * 0.125  # EIP-1559 style
            base_fee = max(
                100_000_000,
                int(self.params.base_fee_per_gas * (1 + fee_adjustment))
            )

            blocks.append({
                "block_time_ms": block_time,
                "gas_used": gas_used,
                "base_fee": base_fee,
            })
        return blocks


# ---------------------------------------------------------------------------
# 2. Network Telemetry Module
# ---------------------------------------------------------------------------

class TelemetryModule:
    """
    Deterministically computes KPIs from an epoch's finalized block data.
    In a real implementation every node runs this calculation independently
    and arrives at the same result, making the KPI vector verifiable.
    """

    def __init__(self, validators: List[Validator], rng: random.Random) -> None:
        self.validators = validators
        self.rng = rng

    def calculate_kpis(
        self,
        epoch: int,
        blocks: List[Dict],
        params: NetworkParams,
        mempool_trend: float,
    ) -> EpochKPIs:
        block_times = [b["block_time_ms"] for b in blocks]
        utilisations = [b["gas_used"] / params.block_gas_limit for b in blocks]
        fees = [b["base_fee"] for b in blocks]

        slashing = sum(
            1 for _ in range(len(self.validators))
            if self.rng.random() < 0.005  # 0.5% chance per validator per epoch
        )

        return EpochKPIs(
            epoch=epoch,
            avg_block_time_ms=statistics.mean(block_times),
            block_time_variance_ms=statistics.variance(block_times)
            if len(block_times) > 1 else 0.0,
            avg_utilization=statistics.mean(utilisations),
            avg_base_fee=int(statistics.mean(fees)),
            validator_count=len(self.validators),
            total_staked_ratio=sum(v.stake for v in self.validators),
            mempool_size_trend=mempool_trend,
            slashing_events=slashing,
        )


# ---------------------------------------------------------------------------
# 3. AI Advisory Module (rule-based)
# ---------------------------------------------------------------------------

class AIAdvisoryModule:
    """
    Rule-based advisor.  Each rule maps a KPI condition to a parameter
    adjustment proposal.  This is the Phase 1 implementation described in
    the whitepaper; it is easily extensible to ML-based decision logic.

    Rules (matching whitepaper examples + sensible extensions):
      R1 – Low utilisation + low fees  → increase block_gas_limit by 5 %
      R2 – High utilisation            → decrease block_gas_limit by 5 %
      R3 – Base fee >> target          → decrease base_fee_per_gas by 10 %
      R4 – Base fee << target          → increase base_fee_per_gas by 5 %
    """

    MIN_FEE_TARGET: int = 800_000_000    # 0.8 Gwei
    MAX_FEE_TARGET: int = 5_000_000_000  # 5 Gwei
    LOW_UTIL_THRESHOLD: float = 0.40
    HIGH_UTIL_THRESHOLD: float = 0.80

    def __init__(self) -> None:
        self._next_proposal_id: int = 1
        self._low_util_streak: int = 0   # consecutive low-utilisation epochs
        self._high_util_streak: int = 0

    def analyze_and_propose(
        self,
        kpis: EpochKPIs,
        params: NetworkParams,
    ) -> Optional[Proposal]:
        """Return a Proposal if any rule fires, otherwise None."""

        # Track utilisation streaks
        if kpis.avg_utilization < self.LOW_UTIL_THRESHOLD:
            self._low_util_streak += 1
            self._high_util_streak = 0
        elif kpis.avg_utilization > self.HIGH_UTIL_THRESHOLD:
            self._high_util_streak += 1
            self._low_util_streak = 0
        else:
            self._low_util_streak = 0
            self._high_util_streak = 0

        # R1: sustained low utilisation and cheap fees → grow block size
        if (
            self._low_util_streak >= 3
            and kpis.avg_base_fee < self.MIN_FEE_TARGET
        ):
            new_val = int(params.block_gas_limit * 1.05)
            return self._make_proposal(
                kpis,
                "block_gas_limit",
                params.block_gas_limit,
                new_val,
                "Low utilization (3 epochs) and low fees: increase block gas limit by 5%",
            )

        # R2: sustained high utilisation → shrink block size to ease pressure
        if self._high_util_streak >= 2:
            new_val = int(params.block_gas_limit * 0.95)
            return self._make_proposal(
                kpis,
                "block_gas_limit",
                params.block_gas_limit,
                new_val,
                "High utilization (2 epochs): decrease block gas limit by 5%",
            )

        # R3: base fee well above target → reduce base fee parameter
        if kpis.avg_base_fee > self.MAX_FEE_TARGET:
            new_val = int(params.base_fee_per_gas * 0.90)
            return self._make_proposal(
                kpis,
                "base_fee_per_gas",
                params.base_fee_per_gas,
                new_val,
                "Base fee exceeded max target: decrease base_fee_per_gas by 10%",
            )

        # R4: base fee well below target → increase base fee parameter
        if kpis.avg_base_fee < self.MIN_FEE_TARGET:
            new_val = int(params.base_fee_per_gas * 1.05)
            return self._make_proposal(
                kpis,
                "base_fee_per_gas",
                params.base_fee_per_gas,
                new_val,
                "Base fee below min target: increase base_fee_per_gas by 5%",
            )

        return None

    # ------------------------------------------------------------------
    def _make_proposal(
        self,
        kpis: EpochKPIs,
        parameter: str,
        current_value: int,
        proposed_value: int,
        rationale: str,
    ) -> Proposal:
        pid = self._next_proposal_id
        self._next_proposal_id += 1
        return Proposal(
            proposal_id=pid,
            epoch_submitted=kpis.epoch,
            parameter=parameter,
            current_value=current_value,
            proposed_value=proposed_value,
            rationale=rationale,
            activation_epoch=kpis.epoch + 2,  # activate 2 epochs after ratification
        )


# ---------------------------------------------------------------------------
# 4. Governance Layer
# ---------------------------------------------------------------------------

class GovernanceLayer:
    """
    On-chain stake-weighted voting.

    Each validator votes Approve or Reject based on:
      - whether the change magnitude exceeds their conservatism threshold,
      - a random component representing imperfect information.

    Thresholds (whitepaper-aligned defaults):
      quorum   = 66% of total staked weight must vote.
      approval = 51% of voting stake must Approve.
    """

    QUORUM: float = 0.66
    APPROVAL: float = 0.51

    def __init__(self, validators: List[Validator], rng: random.Random) -> None:
        self.validators = validators
        self.rng = rng
        self._pending: List[Proposal] = []
        self._history: List[Proposal] = []

    def __init__(self, validators: List[Validator], rng: random.Random) -> None:
        self.validators = validators
        self.rng = rng
        self._pending: List[Proposal] = []
        self._history: List[Proposal] = []

    def register_proposal(self, proposal: Proposal) -> None:
        print(
            f"    [Gov] Proposal #{proposal.proposal_id} registered: "
            f"{proposal.parameter} {proposal.current_value:,} → "
            f"{proposal.proposed_value:,}  ('{proposal.rationale}')"
        )
        self._pending.append(proposal)

    def run_voting_epoch(self, current_epoch: int) -> List[Proposal]:
        """
        Tally votes for all proposals whose voting window has closed
        (one epoch after submission).  Returns newly resolved proposals.
        """
        resolved = []
        still_pending = []

        for proposal in self._pending:
            if current_epoch <= proposal.epoch_submitted:
                still_pending.append(proposal)
                continue

            # Voting epoch has ended — tally
            for validator in self.validators:
                if self.rng.random() < 0.10:
                    continue  # abstain (10 % chance per validator)
                approve = self._vote(validator, proposal)
                if approve:
                    proposal.votes_approve += validator.stake
                else:
                    proposal.votes_reject += validator.stake

            total_voted = proposal.votes_approve + proposal.votes_reject
            total_stake = sum(v.stake for v in self.validators)
            quorum_met = (total_voted / total_stake) >= self.QUORUM
            approval_met = (
                (proposal.votes_approve / total_voted) >= self.APPROVAL
                if total_voted > 0
                else False
            )

            if quorum_met and approval_met:
                proposal.outcome = "passed"
            else:
                proposal.outcome = "failed"

            resolved.append(proposal)
            self._history.append(proposal)

        self._pending = still_pending
        return resolved

    def _vote(self, validator: Validator, proposal: Proposal) -> bool:
        """Simulate a validator's vote."""
        change_pct = abs(proposal.proposed_value - proposal.current_value) / max(
            proposal.current_value, 1
        )
        # Conservative validators reject changes >3%
        if validator.conservative and change_pct > 0.03:
            return False
        # Otherwise approve with probability inversely proportional to change size
        approval_prob = max(0.3, 0.90 - change_pct * 2)
        return self.rng.random() < approval_prob

    @property
    def history(self) -> List[Proposal]:
        return list(self._history)


# ---------------------------------------------------------------------------
# Simulation Orchestrator
# ---------------------------------------------------------------------------

class LalaProtocolSimulation:
    """
    Runs N epochs of the Lala Protocol adaptation loop:
    Block production → Telemetry → AI Advisory → Governance → Activation.
    """

    def __init__(self, epochs: int = 30, seed: Optional[int] = None) -> None:
        self.epochs = epochs
        self.rng = random.Random(seed)

        # Initial network parameters
        self.params = NetworkParams()

        # Validator set: 10 validators with varying stake and conservatism
        total_stake = 100.0
        stakes = sorted(
            [self.rng.uniform(5, 20) for _ in range(10)], reverse=True
        )
        normalised = [s / sum(stakes) for s in stakes]
        self.validators = [
            Validator(
                address=f"val{i:02d}",
                stake=normalised[i],
                conservative=(i >= 7),  # last 3 validators are conservative
            )
            for i in range(10)
        ]

        self.consensus = BaseConsensusLayer(self.params, self.rng)
        self.telemetry = TelemetryModule(self.validators, self.rng)
        self.ai_module = AIAdvisoryModule()
        self.governance = GovernanceLayer(self.validators, self.rng)

        # Pending parameter activations: epoch → (param, value)
        self._scheduled: Dict[int, tuple] = {}

        self._kpi_history: List[EpochKPIs] = []

    # ------------------------------------------------------------------

    def _demand_for_epoch(self, epoch: int) -> float:
        """
        Synthetic demand curve:
          epochs  1–10  : low demand (0.30)
          epochs 11–20  : high demand spike (0.90)
          epochs 21–N   : moderate demand (0.55)
        """
        if epoch <= 10:
            raw = 0.30 + self.rng.gauss(0, 0.05)
        elif epoch <= 20:
            raw = 0.90 + self.rng.gauss(0, 0.05)
        else:
            raw = 0.55 + self.rng.gauss(0, 0.05)
        return max(0.0, raw)

    def _apply_scheduled_activations(self, epoch: int) -> None:
        if epoch in self._scheduled:
            param, value = self._scheduled.pop(epoch)
            setattr(self.params, param, value)
            print(f"  *** Epoch {epoch}: Parameter ACTIVATED — {param} = {value:,} ***")
            # Sync consensus layer
            self.consensus.params = self.params

    def run(self) -> None:
        print("=" * 70)
        print(" Lala Protocol — Adaptation Loop Simulation")
        print("=" * 70)
        print(f"Initial params: {self.params}\n")

        for epoch in range(1, self.epochs + 1):
            print(f"\n── Epoch {epoch:03d} {'─' * 50}")

            # 0. Apply any scheduled parameter activations
            self._apply_scheduled_activations(epoch)

            # 1. Base Consensus Layer: produce blocks
            demand = self._demand_for_epoch(epoch)
            blocks = self.consensus.produce_epoch_blocks(demand)

            # 2. Telemetry Module: compute KPIs
            mempool_trend = (demand - 0.5) * 10  # simple heuristic
            kpis = self.telemetry.calculate_kpis(
                epoch, blocks, self.params, mempool_trend
            )
            self._kpi_history.append(kpis)

            print(
                f"  KPIs  util={kpis.avg_utilization:.1%}  "
                f"fee={kpis.avg_base_fee / 1e9:.3f} Gwei  "
                f"blk_time={kpis.avg_block_time_ms:.0f} ms  "
                f"demand≈{demand:.2f}"
            )

            # 3. AI Advisory Module: analyse and (maybe) propose
            proposal = self.ai_module.analyze_and_propose(kpis, self.params)
            if proposal:
                self.governance.register_proposal(proposal)

            # 4. Governance Layer: tally any open votes
            resolved = self.governance.run_voting_epoch(epoch)
            for p in resolved:
                status = "✅ PASSED" if p.outcome == "passed" else "❌ FAILED"
                print(
                    f"    [Gov] Proposal #{p.proposal_id} {status}  "
                    f"(approve={p.votes_approve:.1%}, reject={p.votes_reject:.1%})"
                )
                if p.outcome == "passed":
                    self._scheduled[p.activation_epoch] = (
                        p.parameter,
                        p.proposed_value,
                    )
                    print(
                        f"    [Gov] Scheduled activation of {p.parameter}="
                        f"{p.proposed_value:,} at epoch {p.activation_epoch}"
                    )

        self._print_summary()

    # ------------------------------------------------------------------

    def _print_summary(self) -> None:
        print("\n" + "=" * 70)
        print(" SIMULATION SUMMARY")
        print("=" * 70)

        print(f"\nFinal network parameters:")
        print(f"  block_gas_limit    : {self.params.block_gas_limit:,}")
        print(f"  base_fee_per_gas   : {self.params.base_fee_per_gas / 1e9:.3f} Gwei")
        print(f"  target_block_time  : {self.params.target_block_time_ms:,} ms")

        passed = [p for p in self.governance.history if p.outcome == "passed"]
        failed = [p for p in self.governance.history if p.outcome == "failed"]
        print(f"\nGovernance outcomes over {self.epochs} epochs:")
        print(f"  Proposals passed : {len(passed)}")
        print(f"  Proposals failed : {len(failed)}")

        if passed:
            print("\nRatified parameter changes:")
            for p in passed:
                direction = "↑" if p.proposed_value > p.current_value else "↓"
                pct = (p.proposed_value - p.current_value) / p.current_value * 100
                print(
                    f"  Epoch {p.epoch_submitted:3d}  {p.parameter:25s} "
                    f"{direction} {pct:+.1f}%  ({p.rationale})"
                )

        # KPI trend
        if self._kpi_history:
            utils = [k.avg_utilization for k in self._kpi_history]
            fees = [k.avg_base_fee / 1e9 for k in self._kpi_history]
            print(
                f"\nKPI averages across all epochs:"
                f"\n  Block utilization : {statistics.mean(utils):.1%}"
                f"\n  Base fee          : {statistics.mean(fees):.3f} Gwei"
            )

        print(
            "\nConclusion: The adaptation loop executed successfully. "
            "The AI Advisory Module proposed changes in response to network "
            "conditions, and the Governance Layer ratified those that met "
            "quorum and approval thresholds."
        )
        print("=" * 70)


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Lala Protocol Adaptation Loop Simulation"
    )
    parser.add_argument(
        "--epochs", type=int, default=30, help="Number of epochs to simulate (default: 30)"
    )
    parser.add_argument(
        "--seed", type=int, default=None, help="Random seed for reproducibility"
    )
    args = parser.parse_args()

    sim = LalaProtocolSimulation(epochs=args.epochs, seed=args.seed)
    sim.run()


if __name__ == "__main__":
    main()
